version: '3.9'

services:

  web:
    # This is so cool, it hides the apache service running along side with php itself.
    # exactly like this one : https://hub.docker.com/r/webdevops/php-nginx
    image: php:8.2-apache
    ports:
      - "82:80"
    depends_on:
      - db
    volumes:
      - ./:/var/www/html

  db:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: lamp_db
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
